# yourl.cloud - Google App Engine Configuration (Simplified)
# ======================================================
# 
# Yourl-Cloud Inc. - Simple Domain Display Service
# Session ID: f1d78acb-de07-46e0-bfa7-f5b75e3c0c49

runtime: nodejs18
service: yourl-cloud

env_variables:
  NODE_ENV: "production"
  SESSION_ID: "f1d78acb-de07-46e0-bfa7-f5b75e3c0c49"
  ORGANIZATION: "Yourl-Cloud Inc."

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 5

resources:
  cpu: 0.5
  memory_gb: 0.25
  disk_size_gb: 1

handlers:
  # Serve static files
  - url: /(.*\.(gif|png|jpg|css|js|ico|woff|woff2|ttf|eot|svg))
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|css|js|ico|woff|woff2|ttf|eot|svg)
    secure: always

  # Serve HTML files
  - url: /(.*\.html)
    static_files: public/\1
    upload: public/.*\.html
    secure: always

  # Default handler - serve index.html
  - url: /.*
    static_files: public/index.html
    upload: public/index.html
    secure: always
