steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/clipboard-bridge', '-f', 'Dockerfile.clipboard', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/clipboard-bridge']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'clipboard-bridge'
      - '--image'
      - 'gcr.io/$PROJECT_ID/clipboard-bridge'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'

  # Create domain mapping for cb.yourl.cloud
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'domain-mappings'
      - 'create'
      - '--service'
      - 'clipboard-bridge'
      - '--domain'
      - 'cb.yourl.cloud'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'

images:
  - 'gcr.io/$PROJECT_ID/clipboard-bridge'

timeout: '1800s'
