# Google Cloud Build configuration for yourl.cloud
# Following Google Cloud Run best practices and myl.zip ethical standards
#
# References:
# - Cloud Build documentation: https://cloud.google.com/build/docs
# - Cloud Run deployment: https://cloud.google.com/run/docs/deploying
# - Container best practices: https://cloud.google.com/solutions/best-practices-for-building-containers

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/yourl-cloud:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/yourl-cloud:latest',
      '.'
    ]
    id: 'build-image'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/yourl-cloud:$COMMIT_SHA']
    id: 'push-image'
    waitFor: ['build-image']

  # Deploy to Cloud Run with enhanced security
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'yourl-cloud',
      '--image', 'gcr.io/$PROJECT_ID/yourl-cloud:$COMMIT_SHA',
      '--region', 'us-west1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--min-instances', '0',
      '--timeout', '300',
      '--concurrency', '80',
      '--set-env-vars', 'SESSION_ID=f1d78acb-de07-46e0-bfa7-f5b75e3c0c49,FORCE_HTTPS=true,REQUIRE_IPV6=true',
      '--labels', 'service=yourl-cloud,ethics=myl-zip-compliant,security=https-ipv6-only',
      '--ingress', 'all',
      '--execution-environment', 'gen2',
      '--service-account', 'yourl-cloud-service@$PROJECT_ID.iam.gserviceaccount.com'
    ]
    id: 'deploy-service'
    waitFor: ['push-image']

  # Configure custom domain with SSL certificate (if available)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'domain-mappings', 'create',
      '--service', 'yourl-cloud',
      '--domain', 'yourl.cloud',
      '--region', 'us-west1',
      '--force-override'
    ]
    id: 'configure-domain'
    waitFor: ['deploy-service']

# Options for build optimization
options:
  # Use faster machine type for builds
  machineType: 'E2_HIGHCPU_8'
  # Enable logging for better debugging
  logging: CLOUD_LOGGING_ONLY
  # Substitute environment variables
  substitution_option: 'ALLOW_LOOSE'

# Substitute variables
substitutions:
  _SERVICE_NAME: 'yourl-cloud'
  _REGION: 'us-west1'

# Build timeout (max 20 minutes)
timeout: '1200s'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/yourl-cloud:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/yourl-cloud:latest'
