# yourl.cloud - Google Cloud Build Configuration
# ============================================
# 
# Yourl-Cloud Inc. - CI/CD Pipeline
# Session ID: f1d78acb-de07-46e0-bfa7-f5b75e3c0c49

steps:
  # Build the application
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/yourl-cloud:$COMMIT_SHA', '.']
    dir: '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/yourl-cloud:$COMMIT_SHA']

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - app
      - deploy
      - app.yaml
      - --version=$COMMIT_SHA
      - --project=$PROJECT_ID
      - --quiet

  # Set the new version as default
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - app
      - versions
      - migrate
      - $COMMIT_SHA
      - --project=$PROJECT_ID
      - --quiet

  # Clean up old versions (keep last 5)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - app
      - versions
      - delete
      - --service=yourl-cloud
      - --project=$PROJECT_ID
      - --quiet
    allowFailure: true

images:
  - 'gcr.io/$PROJECT_ID/yourl-cloud:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _REGION: 'us-central1'
  _SERVICE: 'yourl-cloud'

timeout: '1200s'
