name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: yourl-cloud
  REGION: us-west1

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-west1-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t us-west1-docker.pkg.dev/$PROJECT_ID/yourl-cloud/$SERVICE_NAME:$GITHUB_SHA .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push us-west1-docker.pkg.dev/$PROJECT_ID/yourl-cloud/$SERVICE_NAME:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image us-west1-docker.pkg.dev/$PROJECT_ID/yourl-cloud/$SERVICE_NAME:$GITHUB_SHA \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --port 8080 \
          --memory 1Gi \
          --cpu 1 \
          --max-instances 10 \
          --min-instances 0 \
          --timeout 300 \
          --concurrency 80 \
          --set-env-vars="SESSION_ID=f1d78acb-de07-46e0-bfa7-f5b75e3c0c49"

    - name: Show service URL
      run: |
        echo "Service deployed to:"
        gcloud run services describe $SERVICE_NAME --region $REGION --format 'value(status.url)'

  notify-success:
    name: Notify Deployment Success
    runs-on: ubuntu-latest
    needs: deploy
    if: success()
    
    steps:
    - name: Comment on PR (if applicable)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const prNumber = context.payload.pull_request.number;
          const commentBody = `✅ **Deployment Successful!**
          
          Your changes have been successfully deployed to Google Cloud Run.
          
          - **Service**: yourl-cloud
          - **Region**: us-west1  
          - **Commit**: ${context.sha.substring(0, 7)}
          - **Session ID**: f1d78acb-de07-46e0-bfa7-f5b75e3c0c49
          
          The deployment follows myl.zip ethics and standards for responsible AI service delivery.`
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: commentBody
          });

  notify-failure:
    name: Notify Deployment Failure
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()
    
    steps:
    - name: Comment on PR (if applicable)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const prNumber = context.payload.pull_request.number;
          const commentBody = `❌ **Deployment Failed**
          
          There was an issue deploying your changes to Google Cloud Run.
          
          - **Service**: yourl-cloud
          - **Region**: us-west1
          - **Commit**: ${context.sha.substring(0, 7)}
          
          Please check the [Actions logs](https://github.com/${context.repo.owner}/${context.repo.repo}/actions) for details.`
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: commentBody
          });
