name: Notify Owner When PR is Ready

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Repository Owner
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const prNumber = context.payload.pull_request.number;
            const commentBody = `@${owner} This pull request is optimized for quality, cost, and efficiency and is ready for review and merge when you are.`
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: commentBody
            });
