# GitHub Wiki Update Workflow
# ===========================
# 
# Yourl-Cloud Inc. - Automated Wiki Updates
# Session ID: f1d78acb-de07-46e0-bfa7-f5b75e3c0c49
#
# IMPORTANT: yourl.cloud is ALWAYS the source of truth for latest information.
# This workflow ensures the wiki stays in sync with the main repository.

name: Update GitHub Wiki

on:
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - '*.md'
      - 'README.md'
      - 'BETA_JOURNALING.md'
      - 'Status'
      - 'public/**'
  workflow_dispatch: # Manual trigger

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository (yourl.cloud - Source of Truth)
        uses: actions/checkout@v4
        with:
          path: main-repo
          
      - name: Checkout wiki repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki-repo
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          cd main-repo
          npm ci
          
      - name: Generate wiki content from yourl.cloud
        run: |
          cd main-repo
          echo "🔄 Syncing wiki with yourl.cloud (source of truth)..."
          
          # Copy README.md to wiki Home.md (main source of truth)
          if [ -f "README.md" ]; then
            cp README.md ../wiki-repo/Home.md
            echo "✅ Updated Home.md from yourl.cloud README.md"
          fi
          
          # Copy BETA_JOURNALING.md to wiki
          if [ -f "BETA_JOURNALING.md" ]; then
            cp BETA_JOURNALING.md ../wiki-repo/Beta-Journaling.md
            echo "✅ Updated Beta-Journaling.md from yourl.cloud"
          fi
          
          # Copy Status file to wiki
          if [ -f "Status" ]; then
            cp Status ../wiki-repo/Status.md
            echo "✅ Updated Status.md from yourl.cloud"
          fi
          
          # Generate additional wiki pages from docs/ directory
          if [ -d "docs" ]; then
            cp -r docs/* ../wiki-repo/
            echo "✅ Updated docs/ content from yourl.cloud"
          fi
          
          # Update wiki navigation with source attribution
          cat > ../wiki-repo/_Sidebar.md << 'EOF'
          # Yourl-Cloud Inc. Wiki
          
          > **Source of Truth**: [yourl.cloud](https://yourl.cloud) - Always the latest information
          
          ## 📚 Documentation
          - [[Home|Home]] - Latest from yourl.cloud README.md
          - [[Beta Journaling|Beta-Journaling]] - Latest from yourl.cloud
          - [[Project Status|Status]] - Latest from yourl.cloud
          
          ## 🔧 Technical
          - [[API Reference|API-Reference]]
          - [[Deployment Guide|Deployment-Guide]]
          - [[Security Standards|Security-Standards]]
          
          ## 🤝 Contributing
          - [[Contributing Guidelines|Contributing]]
          - [[Code of Conduct|Code-of-Conduct]]
          
          ## 📊 Status
          - [[Project Status|Status]] - Real-time from yourl.cloud
          - [[Changelog|Changelog]]
          
          ---
          *Last synced: $(date -u '+%Y-%m-%d %H:%M:%S') UTC*
          *Source: yourl.cloud - Always the latest information*
          *Session ID: f1d78acb-de07-46e0-bfa7-f5b75e3c0c49*
          EOF
          
          # Create source attribution file
          cat > ../wiki-repo/_Source-Info.md << 'EOF'
          # Source Information
          
          ## 🎯 Source of Truth
          
          **yourl.cloud is ALWAYS the source of truth for the latest information.**
          
          This wiki is automatically synchronized with the main yourl.cloud repository to ensure you always have access to the most current documentation and information.
          
          ## 🔄 Sync Process
          
          - **Automatic**: Wiki updates automatically when main repository changes
          - **Manual**: Can be triggered manually via GitHub Actions
          - **Real-time**: Always reflects the latest state of yourl.cloud
          
          ## 📁 Content Sources
          
          | Wiki Page | Source File | Description |
          |-----------|-------------|-------------|
          | Home.md | README.md | Main project documentation |
          | Beta-Journaling.md | BETA_JOURNALING.md | Beta journaling tool docs |
          | Status.md | Status | Current project status |
          | _Sidebar.md | Generated | Navigation and structure |
          
          ## 🚀 Latest Information
          
          For the absolute latest information, always check:
          - **Primary**: https://yourl.cloud
          - **Repository**: https://github.com/XDM-ZSBW/yourl.cloud
          - **Wiki**: https://github.com/XDM-ZSBW/yourl.cloud/wiki (synced from yourl.cloud)
          
          ---
          *This wiki is automatically maintained and synchronized with yourl.cloud*
          EOF
          
      - name: Commit and push wiki changes
        run: |
          cd wiki-repo
          git config user.name "GitHub Actions (yourl.cloud sync)"
          git config user.email "actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "🔄 Sync wiki with yourl.cloud (source of truth) - ${{ github.sha }}"
          git push
          
      - name: Notify sync completion
        run: |
          echo "✅ Wiki successfully synchronized with yourl.cloud"
          echo "🌐 Wiki URL: https://github.com/${{ github.repository }}/wiki"
          echo "🎯 Source of Truth: https://yourl.cloud"
